version: "3.9"
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: "true"
      DB_HOST: "postgres"
    hostname: "web"
  postgres:
    image: "postgres:13.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      hostname: "postgres"