"""empty message

Revision ID: 5748bdaec489
Revises: 3c9fdf4658ed
Create Date: 2023-02-23 12:30:47.929288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5748bdaec489'
down_revision = '3c9fdf4658ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=0)
    op.create_unique_constraint(None, 'contacts', ['id'])
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=0)
    op.create_unique_constraint(None, 'documents', ['id'])
    op.add_column('email_creds', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('email_creds', sa.Column('pop_port', sa.Integer(), nullable=True))
    op.add_column('email_creds', sa.Column('imap_server', sa.String(length=120), nullable=True))
    op.add_column('email_creds', sa.Column('imap_port', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'email_creds', ['id'])
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'templates', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'vacancy', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'templates', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'email_creds', type_='unique')
    op.drop_column('email_creds', 'imap_port')
    op.drop_column('email_creds', 'imap_server')
    op.drop_column('email_creds', 'pop_port')
    op.drop_column('email_creds', 'smtp_port')
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'contacts', type_='unique')
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
